# Generated by Django 3.2 on 2021-05-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistance',
            old_name='message',
            new_name='address',
        ),
    ]
